### ISSUE TITLE
Channel tabs should have X to close/part channels

### ISSUE THREAD

**Issue by jeto** [Tsarpf/Tsatter#25]

**Comment by Tsarpf** [comment]
https://github.com/Tsarpf/Tsatter/issues/23

This already has the same idea but  I'll leave this open since it specifically talks about a new button.

I don't think the normal bootstrap tabs which are used at the moment have the possibility to add buttons within them, but we'll have to investigate

**Comment by Tsarpf** [comment]
/part implemented, now just need the x button

**Comment by Tsarpf** [comment]
d484f1648b39031006c1d12db1c45f5a9c6a5986
done
