### ISSUE TITLE
Changing to taken nick changes to next anon

### ISSUE THREAD

**Issue by jeto** [Tsarpf/Tsatter#26]
Should inform that nick is taken, not change nick.

**Comment by Tsarpf** [comment]
fixing would be nice but I don't think it's absolutely necessary for 1.0

**Comment by Tsarpf** [comment]
I couldn't find a way to actually disable the functionality from inspircd configs. Weird.

85083d47cf20c0335b45ae8a771ebba369f721a2
However the server now shows a message if the nick was already taken so at least you know what's happening.

I think this is good enough for now, although far from perfect.
