### ISSUE TITLE
Revamp looks. Start using Flat UI?

### ISSUE THREAD

**Issue by Tsarpf** [Tsarpf/Tsatter#33]
http://designmodo.github.io/Flat-UI/

**Comment by juzmach** [comment]
I have added flat-ui into bower.json in my Docker Compose branch, but it can be added separately if you want/need it faster.

**Comment by Tsarpf** [comment]
Nah, there's a lot of other stuff to be done, as long as it's mergeable to
master within something like a month we'll just use what you've already
done.

**Comment by Tsarpf** [comment]
d71cab5a3607dd2a8b7fbe92c668f719f8760bf2

revamps discover page to a state where it's good enough for my eye

(but I'm aesthetically challenged so that doesn't necessarily say much)

**Comment by Tsarpf** [comment]
chat still looks ugly

**Comment by Tsarpf** [comment]
using flat ui, will make other issue for chat revamp
